MoviePointProject/Controllers/CinemaController.cs
using Microsoft.AspNetCore.Mvc;
using MoviePoint.Models;
using MoviePoint.Repository;

namespace MoviePoint.Controllers
{
    public class CinemaController : Controller
    {
        ICinemaRepository cinemaRepository;

        public CinemaController
            (ICinemaRepository _cinRepo)
        {
            cinemaRepository = _cinRepo;
        }

        public IActionResult Index()
        {
            List<Cinema> cinema = cinemaRepository.GetAll();
            return View(cinema);

        }

        [HttpGet]
        public IActionResult Insert()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Insert(Cinema cinema)
        {
            if (ModelState.IsValid == true)
            {
                Cinema NewCinema = new Cinema();
                NewCinema.Name = cinema.Name;
                NewCinema.Logo = cinema.Logo;
                NewCinema.Description = cinema.Description;
                NewCinema.Movies = cinema.Movies;
                NewCinema.Location = cinema.Location;
                cinemaRepository.Insert(NewCinema);
                return RedirectToAction("Index");
            }

            return View(cinema);



        }

        [HttpGet]
        public IActionResult Update(int id)
        {
            Cinema cinema = cinemaRepository.GetById(id);
            return View(cinema);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update(Cinema newCinema, [FromRoute] int id)
        {
            if (ModelState.IsValid == true)
            {
                cinemaRepository.Update(id, newCinema);
                return RedirectToAction("Index");
            }
            return View(newCinema);

        }

        public IActionResult Delete(int id)
        {
            cinemaRepository.Delete(id);
            return RedirectToAction("Index");
        }
    }
}

MoviePointProject/Controllers/MovieController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MoviePoint.Models;
using MoviePoint.Repository;
using MoviePoint.ViewModel;
using NuGet.Protocol.Core.Types;
using static System.Runtime.InteropServices.JavaScript.JSType;

namespace MoviePoint.Controllers
{
	
	public class MovieController : Controller
	{
		IMovieRepository movieRepository;
        IActorRepository actorRepository;
        ICommentsRepository commentsRepository;
        IProducerRepository producerRepository;
        ICinemaRepository cinemaRepository;
        IActorMovieRepository actormovieRepository;



        public MovieController
			(ICommentsRepository _comRepo,IMovieRepository _movRepo, IActorRepository _actRepo, IProducerRepository _proRepo, ICinemaRepository _cinemaRepo, IActorMovieRepository _actmovieRepo)
		{
            movieRepository = _movRepo;
            actorRepository = _actRepo;
            producerRepository = _proRepo;
            cinemaRepository = _cinemaRepo;
            actormovieRepository= _actmovieRepo;
            commentsRepository = _comRepo;
        }

		public IActionResult Index()
		{
			List<Movie> movies = movieRepository.GetAll();
			return View(movies);
		}

		public IActionResult Details(int id)
		{
            List<Comment> comments = commentsRepository.GetComments(id);
			ViewData["Comments"] = comments;
			MovieDetailsViewModel movieModel = new MovieDetailsViewModel();
			Movie movie = movieRepository.GetMovieWithDetails(id);
			movieModel.MovieName = movie.Name;
			movieModel.MovieCategory = movie.Category;
			movieModel.MoviePrice = movie.Price;
			movieModel.MovieEndDate = movie.EndtDate;
			movieModel.MovieStartDate = movie.StartDate;
			movieModel.MovieDescription = movie.Description;
			movieModel.MovieImageUrl = movie.ImageUrl;
			movieModel.CinemaName = movie.Cinema.Name;
			movieModel.CinemaLocation = movie.Cinema.Location;
			movieModel.ProducerName = movie.Producer.FullName;
            
			return View(movieModel);
		}

        [HttpGet]
        public IActionResult Insert()
        {
            MoiveViewModel NewMoive =
                new MoiveViewModel();

            NewMoive.cinemas = cinemaRepository.GetAll();
            NewMoive.producers = producerRepository.GetAll();
            NewMoive.Actor_Movies = actormovieRepository.GetAll();
            NewMoive.AllActors = actorRepository.GetAll();


            return View(NewMoive);

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Insert(MoiveViewModel moiveViewModel)
        {
            
            if (ModelState.IsValid == true)
            {
                Movie movie = new Movie();

                movie.Name = moiveViewModel.Name;
                movie.Description = moiveViewModel.Description;
                movie.Price =(int) moiveViewModel.Price;
                movie.ImageUrl = moiveViewModel.ImageUrl;
                movie.StartDate = moiveViewModel.StartDate;
                movie.EndtDate = moiveViewModel.EndtDate;
                movie.ProducerID = moiveViewModel.ProducerID;
                movie.CinemaID = moiveViewModel.CinemaID;
                movie.Category=moiveViewModel.Category;
                movie.videoURL = moiveViewModel.videoURL;
                moiveViewModel.AllActors = actorRepository.GetAll();
                moiveViewModel.cinemas = cinemaRepository.GetAll();
                moiveViewModel.producers = producerRepository.GetAll();
                moiveViewModel.Actor_Movies = actormovieRepository.GetAll();
              

                movieRepository.Insert(movie);

                List<Actor> actors = new List<Actor>();
                foreach (var ctorid in moiveViewModel.Actors)
                {
                    
                    actors.Add( actorRepository.GetById(ctorid));

                }
                moiveViewModel.ActorsObj = actors;


                foreach (var actorId in moiveViewModel.Actors)
                {
                    var newActorMovie = new Actor_Movie()
                    {
                        MovieID = movie.Id,
                        ActorID = actorId
                    };
                    actormovieRepository.Insert(newActorMovie);
                }
                return RedirectToAction("Index");
            }

            return View(moiveViewModel);
        }



        [HttpGet]
        public IActionResult Update(int id)
        {
            var movie = movieRepository.GetById(id);

            MoiveViewModel NewMoive =
                new MoiveViewModel();
            NewMoive.Name= movie.Name;
            NewMoive.Description = movie.Description;
            NewMoive.Price = movie.Price;
            NewMoive.ImageUrl = movie.ImageUrl;
            NewMoive.StartDate = movie.StartDate;
            NewMoive.EndtDate = movie.EndtDate;
            NewMoive.Category = movie.Category;
            NewMoive.videoURL = movie.videoURL;
            NewMoive.CinemaID = movie.CinemaID;
            NewMoive.ProducerID = movie.ProducerID;

            NewMoive.cinemas = cinemaRepository.GetAll();
            NewMoive.producers = producerRepository.GetAll();
            NewMoive.Actor_Movies = actormovieRepository.GetAll();
            NewMoive.AllActors = actorRepository.GetAll();

            return View(NewMoive);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update(MoiveViewModel moiveViewModel, [FromRoute] int id)
        {
            Movie oldMovie = movieRepository.GetById(id);

            if (ModelState.IsValid == true)
            {
                oldMovie.Name = moiveViewModel.Name;
                oldMovie.Description = moiveViewModel.Description;
                oldMovie.Price = (int)moiveViewModel.Price;
                oldMovie.ImageUrl = moiveViewModel.ImageUrl;
                oldMovie.StartDate = moiveViewModel.StartDate;
                oldMovie.EndtDate = moiveViewModel.EndtDate;
                oldMovie.ProducerID = moiveViewModel.ProducerID;
                oldMovie.CinemaID = moiveViewModel.CinemaID;
                oldMovie.Category = moiveViewModel.Category;
                oldMovie.videoURL = moiveViewModel.videoURL;

                moiveViewModel.AllActors = actorRepository.GetAll();
                moiveViewModel.cinemas = cinemaRepository.GetAll();
                moiveViewModel.producers = producerRepository.GetAll();
                moiveViewModel.Actor_Movies = actormovieRepository.GetAll();


                movieRepository.Update(id,oldMovie);

                List<Actor> actors = new List<Actor>();
                foreach (var ctorid in moiveViewModel.Actors)
                {

                    actors.Add(actorRepository.GetById(ctorid));

                }
                moiveViewModel.ActorsObj = actors;


                foreach (var actorId in moiveViewModel.Actors)
                {
                    var newActorMovie = new Actor_Movie()
                    {
                        MovieID = oldMovie.Id,
                        ActorID = actorId
                    };
                    actormovieRepository.Update(id,newActorMovie);
                }
                return RedirectToAction("Index");
            }

            return View(moiveViewModel);
        }

        public IActionResult Delete(int id)
        {
            List<Actor_Movie> ActorMovie= actormovieRepository.GetByMovieId(id);


			foreach (var actor in ActorMovie)
			{
				actormovieRepository.Delete(actor.ID);
			}
			 movieRepository.Delete(id);

			return RedirectToAction("Index");
        }
    }
}

MoviePointProject/Controllers/NewsController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using MoviePoint.Models;
using MoviePoint.Repository;
using MoviePoint.ViewModel;


namespace MoviePoint.Controllers
{
	public class NewsController : Controller
	{
		IMovieRepository movieRepository;
		ICommentsRepository commentsRepository;
		private readonly UserManager<IdentityUser> userManager;


		public NewsController
			(ICommentsRepository _comRepo, IMovieRepository _movRepo, UserManager<IdentityUser> _userManager)
		{
			movieRepository = _movRepo;
			commentsRepository = _comRepo;
			this.userManager = _userManager;
		}

		public IActionResult Index()
		{
			List<Movie> movies = movieRepository.GetAll();
			return View(movies);
		}

		public IActionResult Details(int id)
		{
            MovieWithUserViewModel movieWithUserViewModel = new MovieWithUserViewModel();
			string userId = userManager.GetUserId(HttpContext.User);

			Movie movie = movieRepository.GetMovieWithDetails(id);
            movieWithUserViewModel.Movie= movie;
			movieWithUserViewModel.UserID = userId;
			movieWithUserViewModel.Comments = commentsRepository.GetComments(id);


			return View(movieWithUserViewModel); 
        }
	}
}

MoviePointProject/Controllers/TicketsController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using MoviePoint.logic.Models;
using MoviePoint.logic.Repository;
using MoviePoint.logic.ViewModel;
using MoviePoint.Models;
using MoviePoint.Repository;
using System.Security.Claims;

namespace MoviePoint.logic.Controllers
{
	public class TicketsController : Controller
	{

		ITicketsRepository ticketsRepository;
		IMovieRepository MovieRepository;
		ICinemaRepository CinemaRepository;
        private readonly UserManager<IdentityUser> userManager;

        MoviePointContext context;
		public TicketsController
			(ITicketsRepository _ticketsRepo, IMovieRepository _movieRepo, ICinemaRepository _cinemaRepo, MoviePointContext _context, UserManager<IdentityUser> _userManager)
		{
			ticketsRepository = _ticketsRepo;
			MovieRepository= _movieRepo;
			CinemaRepository= _cinemaRepo;
			context= _context;
			userManager= _userManager;
		}

		public IActionResult Index()
		{
			List<Tickets> Tickets=new List<Tickets>();
			if ((User.IsInRole("Admin")))
			{
				Tickets = ticketsRepository.GetAll();
			}
			else
			{
				var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
				Tickets = ticketsRepository.GetByUserId(userId);
			}
           
            List<TicketsViewModel> ticketsViewModelsList = new List<TicketsViewModel>();
            //List<Tickets> Tickets = ticketsRepository.GetAll();
            

            foreach (var item in Tickets)
			{
				TicketsViewModel ticketsViewModel = new TicketsViewModel();
				ticketsViewModel.price = MovieRepository.GetById(item.MovieID).Price;
				ticketsViewModel.Quantity = item.Quantity;
				ticketsViewModel.date = item.date;
				ticketsViewModel.CienmaName= CinemaRepository.GetById(item.CinemaID).Name;
				ticketsViewModel.MovieName= MovieRepository.GetById(item.MovieID).Name;
				ticketsViewModel.TotalPrice = item.price * item.Quantity;

				ticketsViewModel.userName = context.Users.FirstOrDefault(x => x.Id == item.userID).UserName;
				ticketsViewModelsList.Add(ticketsViewModel);
			}
			return View(ticketsViewModelsList);

		}

        public IActionResult SendPrice()
        {
           

            return View("Add");
        }
        public IActionResult SendPriceJSON(int MovieID)
        {
            double Moveprice= MovieRepository.GetById(MovieID).Price;

            return Json(Moveprice);
        }


        [HttpGet]
		public IActionResult Add()
		{
            TicketsViewModel ticketsViewModel=new TicketsViewModel();
			ticketsViewModel.MovieList = MovieRepository.GetAll();
            ticketsViewModel.CinemaList= CinemaRepository.GetAll();

            return View(ticketsViewModel);
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult Add(TicketsViewModel ticketsVM)
		{
			if (ModelState.IsValid == true)
			{
				
				Tickets NewTicket = new Tickets();
				NewTicket.price = ticketsVM.price;

                NewTicket.date = ticketsVM.date;
				NewTicket.Quantity = ticketsVM.Quantity;
				NewTicket.CinemaID = int.Parse(ticketsVM.CienmaName); 

                NewTicket.MovieID = int.Parse(ticketsVM.MovieName);
                NewTicket.userID = userManager.GetUserId(HttpContext.User);

                ticketsRepository.Insert(NewTicket);
				return RedirectToAction("Index");
			}

			return View(ticketsVM);



		}

		[HttpGet]
		public IActionResult Edit(int id)
		{
			Tickets tickets = ticketsRepository.GetById(id);
			return View(tickets);
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult Edit(int id, Tickets newtickets)
		{
			if (ModelState.IsValid == true)
			{
				ticketsRepository.Update(id, newtickets);
				return RedirectToAction("Index");
			}
			return View(newtickets);

		}

		public IActionResult Cancel(int id)
		{
			ticketsRepository.Delete(id);
			return RedirectToAction("Index");
		}

		
	}
}

MoviePointProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MoviePoint</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MoviePoint.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MoviePoint</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - MoviePoint - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MoviePointProject/Views/Shared/_NavAndFooterLayout.cshtml
<!DOCTYPE html>

<html>
<head>
		<meta charset="UTF-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>Moviepoint - Online Movie,Vedio and TV Show HTML Template</title>
		<!-- Favicon Icon -->
		<link rel="icon" type="image/png" href="/img/favcion.png" />
		<!-- Bootstrap CSS -->
		<link rel="stylesheet" type="text/css" href="/css/bootstrap.min.css" media="all" />
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.2.3/css/bootstrap-grid.min.css" integrity="sha512-JQksK36WdRekVrvdxNyV3B0Q1huqbTkIQNbz1dlcFVgNynEMRl0F8OSqOGdVppLUDIvsOejhr/W5L3G/b3J+8w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
		<!-- Slick nav CSS -->
		<link rel="stylesheet" type="text/css" href="/css/slicknav.min.css" media="all" />
		<!-- Iconfont CSS -->
		<link rel="stylesheet" type="text/css" href="/css/icofont.css" media="all" />
		<!-- Owl carousel CSS -->
		<link rel="stylesheet" type="text/css" href="/css/owl.carousel.css">
		<!-- Popup CSS -->
		<link rel="stylesheet" type="text/css" href="/css/magnific-popup.css">
		<!-- Main style CSS -->
		<link rel="stylesheet" type="text/css" href="/css/style.css" media="all" />
		<!-- Responsive CSS -->
		<link rel="stylesheet" type="text/css" href="/css/responsive.css" media="all" />
		<!--[if lt IE 9]>
		  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
		  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
		<![endif]-->
	</head>
<body>
	<header class="header">
		<div class="container">
			<div class="header-area">
				<div class="logo">
					<a href="index-2.html"><img src="/img/logo.png" alt="logo" /></a>
				</div>
				<div class="header-right">
					<form action="#">
						<select>
							<option value="Movies">Movies</option>
							<option value="Actors">Actors</option>
							<option value="Cinemas">Cinemas</option>
						</select>
						<input type="text" />
						<button><i class="icofont icofont-search"></i></button>
					</form>
					<ul>
						@if(User.IsInRole("Admin"))
						{
							<li><a href="#">Welcome @User.Identity.Name</a></li>
							<li><a asp-action="Registration" asp-controller="Admin">Sign Up</a></li>
							<li><a asp-action="signOut" asp-controller="Account">Sign Out</a></li>
						}
						else if (User.Identity.IsAuthenticated)
						{
							<li><a href="#">Welcome @User.Identity.Name</a></li>
							<li><a asp-action="signOut" asp-controller="Account">Sign Out</a></li>
						}
						else
						{
							<li><a href="#">Welcome</a></li>

							<li><a asp-action="Login" asp-controller="Account">Login</a></li>
							<li><a asp-action="Registration" asp-controller="Account">Sign Up</a></li>
						}
						
					</ul>
				</div>
				<div class="menu-area">
					<div class="responsive-menu"></div>
					<div class="mainmenu">
						<ul id="primary-menu">
							<li><a asp-action="Home" asp-controller="Home">Home</a></li>
							<li><a asp-action="Index" asp-controller="Movie">Movies</a></li>
							<li><a asp-action="Index" asp-controller="Actors">Actors</a></li>
						    <li><a asp-action="Index" asp-controller="Cinema">Cinemas</a></li>
							<li><a asp-action="Index" asp-controller="Producer">Producers</a></li>
							<li><a asp-action="Index" asp-controller="News">News</a></li>


							<li>
								<a asp-action="Index" asp-controller="Tickets">All Tickets</a>
								@*<ul>
									<li><a href="blog-details.html">Blog Details</a></li>
									<li><a href="movie-details.html">Movie Details</a></li>
								</ul>*@
							</li>
@*						<li><a asp-action="Add" asp-controller="Tickets" class="theme-btn"><i class="icofont icofont-ticket"></i> Tickets</a></li>
*@
							<li class="theme-btn text-center"><a asp-action="Add" asp-controller="Tickets"><i class="icofont icofont-ticket"></i>Tickets</a></li>
					</ul>
					</div>
				</div>
			</div>
		</div>
	</header>

    <div>
        @RenderBody()
    </div>

	<footer class="footer" style="margin-top:5%">
		<div class="container">
			<div class="row">
				<div class="col-lg-3 col-sm-6">
					<div class="widget">
						<img src="/img/logo.png" alt="about" />
						<p>7th Harley Place, London W1G 8LZ United Kingdom</p>
						<h6><span>Call us: </span>(+880) 111 222 3456</h6>
					</div>
				</div>
				<div class="col-lg-3 col-sm-6">
					<div class="widget">
						<h4>Legal</h4>
						<ul>
							<li><a href="#">Terms of Use</a></li>
							<li><a href="#">Privacy Policy</a></li>
							<li><a href="#">Security</a></li>
						</ul>
					</div>
				</div>
				<div class="col-lg-3 col-sm-6">
					<div class="widget">
						<h4>Account</h4>
						<ul>
							<li><a href="#">My Account</a></li>
							<li><a href="#">Watchlist</a></li>
							<li><a href="#">Collections</a></li>
							<li><a href="#">User Guide</a></li>
						</ul>
					</div>
				</div>
				<div class="col-lg-3 col-sm-6">
					<div class="widget">
						<h4>Newsletter</h4>
						<p>Subscribe to our newsletter system now to get latest news from us.</p>
						<form action="#">
							<input type="text" placeholder="Enter your email.." />
							<button>SUBSCRIBE NOW</button>
						</form>
					</div>
				</div>
			</div>
			<hr />
		</div>
		<div class="copyright">
			<div class="container">
				<div class="row">
					<div class="col-lg-6 text-center text-lg-left">
						<div class="copyright-content">
							<p><a target="_blank" href="https://www.templateshub.net">Templates Hub</a></p>
						</div>
					</div>
					<div class="col-lg-6 text-center text-lg-right">
						<div class="copyright-content">
							<a href="#" class="scrollToTop">
								Back to top<i class="icofont icofont-arrow-up"></i>
							</a>
						</div>
					</div>
				</div>
			</div>
		</div>
	</footer>
	<!-- jquery main JS -->
	<script src="/js/jquery.min.js"></script>
	<!-- Bootstrap JS -->
	<script src="/js/bootstrap.min.js"></script>
	<!-- Slick nav JS -->
	<script src="/js/jquery.slicknav.min.js"></script>
	<!-- owl carousel JS -->
	<script src="/js/owl.carousel.min.js"></script>
	<!-- Popup JS -->
	<script src="/js/jquery.magnific-popup.min.js"></script>
	<!-- Isotope JS -->
	<script src="/js/isotope.pkgd.min.js"></script>
	<!-- main JS -->
	<script src="/js/main.js"></script>
	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>