MoviePointProject/Models/Producer.cs
namespace MoviePoint.Models
{
    public class Producer
    {
        public int Id { get; set; }

        public string ProfilePicture { get; set; }

        public string FullName { get; set; }

        public string Bio { get; set; }

        public virtual List<Movie>? Movies { get; set; }
    }
}

MoviePointProject/Controllers/ProducerController.cs
using Microsoft.AspNetCore.Mvc;
using MoviePoint.Models;
using MoviePoint.Repository;

namespace MoviePoint.Controllers
{
    public class ProducerController : Controller
    {
        IProducerRepository producerRepository;

        public ProducerController
            (IProducerRepository _proRepo)
        {
            producerRepository = _proRepo;
        }

        public IActionResult Index()
        {
            List<Producer> producer = producerRepository.GetAll();
            return View(producer);

        }

        [HttpGet]
        public IActionResult Insert()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Insert(Producer producer)
        {
            if (ModelState.IsValid == true)
            {
                Producer NewProducer = new Producer();
                NewProducer.FullName = producer.FullName;
                NewProducer.Bio = producer.Bio;
                NewProducer.ProfilePicture = producer.ProfilePicture;

                producerRepository.Insert(NewProducer);
                return RedirectToAction("Index");
            }

            return View(producer);



        }

        [HttpGet]
        public IActionResult Update(int id)
        {
            Producer producer = producerRepository.GetById(id);
            return View(producer);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update(Producer newProducer, [FromRoute] int id)
        {
            if (ModelState.IsValid == true)
            {
                producerRepository.Update(id, newProducer);
                return RedirectToAction("Index");
            }
            return View(newProducer);

        }

        public IActionResult Delete(int id)
        {
            producerRepository.Delete(id);
            return RedirectToAction("Index");
        }
    }
}

MoviePointProject/Views/Producer/Index.cshtml
@model IEnumerable<MoviePoint.Models.Producer>

	@{
		ViewData["Title"] = "Index";
		Layout = "_NavAndFooterLayout";
	}

	<section class="breadcrumb-area">
		<div class="container">
			<div class="row">
				<div class="col-lg-12">
					<div class="breadcrumb-area-content">
					<h1>Producers Page</h1>
					</div>
				</div>
			</div>
		</div>
	</section>

	<section class="portfolio-area pt-60">
		<div class="container">
		@if (User.IsInRole("Admin"))
		{
			<div class="mx-auto text-center col-md-4">
				<a class="theme-btn" style="width:100%;" asp-action="Insert" asp-controller="Producer">Add New Producer</a>
			</div>
		}
		
			<div class="row portfolio-item">
				@foreach (var item in Model)
				{
					<div class="col-lg-3 col-md-4 col-sm-12 soon released">
					<div class="single-portfolio" style="margin-bottom:20px;">
						<div class="single-portfolio-img">
								<img src="@item.ProfilePicture" alt="portfolio" />
							</div>
							<div class="portfolio-content">
								<h2 class="my-3">@item.FullName</h2>
								<p class="mb-3">@item.Bio</p>
							</div>
						@if (User.IsInRole("Admin"))
						{
							<div class="d-flex justify-content-around">
								<a class="theme-btn" asp-action="Update" asp-controller="Producer" asp-route-id="@item.Id">Edit</a>
								<a class="theme-btn" asp-action="Delete" asp-controller="Producer" asp-route-id="@item.Id">Delete</a>
							</div>
						}
						
						</div>

					</div>
				}
			</div>
		</div>
	</section>

@section Scripts {
	@{
		await Html.RenderPartialAsync("_ValidationScriptsPartial");
	}
}

MoviePointProject/Views/Producer/Insert.cshtml
@model MoviePoint.Models.Producer

@{
    ViewData["Title"] = "Insert";
    Layout = "_NavAndFooterLayout";
}

<section class="breadcrumb-area">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="breadcrumb-area-content">
                    <h1>Add Producer Page</h1>
                </div>
            </div>
        </div>
    </div>
</section>
<div class="container">
    <div class="row" style="position:relative">
        <div class="col-md-5 mb-2 mx-auto">
            <form asp-action="Insert" style="position: relative;top: 50px;">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FullName" class="control-label"></label>
                <input asp-for="FullName" class="form-control" />
                <span asp-validation-for="FullName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProfilePicture" class="control-label"></label>
                <input asp-for="ProfilePicture" class="form-control" />
                <span asp-validation-for="ProfilePicture" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Bio" class="control-label"></label>
                <input asp-for="Bio" class="form-control" />
                <span asp-validation-for="Bio" class="text-danger"></span>
            </div>
            <div class="form-group">
                    <input type="submit" value="Add" class="theme-btn mb-3" />
            </div>
            <div>
                <a asp-action="Index">Back to List</a>
            </div>
        </form>
    </div>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MoviePointProject/Views/Producer/Update.cshtml
@model MoviePoint.Models.Producer

@{
    ViewData["Title"] = "Update";
    Layout = "_NavAndFooterLayout";
}

<section class="breadcrumb-area">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="breadcrumb-area-content">
                    <h1>Edit Producer Page</h1>
                </div>
            </div>
        </div>
    </div>
</section>
<div class="container">
    <div class="row" style="position:relative">
        <div class="col-md-5 mb-2 mx-auto">
            <form asp-action="Update" style="position: relative;top: 50px;">
                <div asp-validation-summary="All" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="FullName" class="control-label"></label>
                    <input asp-for="FullName" class="form-control" />
                    <span asp-validation-for="FullName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ProfilePicture" class="control-label"></label>
                    <input asp-for="ProfilePicture" class="form-control" />
                    <span asp-validation-for="ProfilePicture" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Bio" class="control-label"></label>
                    <input asp-for="Bio" class="form-control" />
                    <span asp-validation-for="Bio" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Save" class="theme-btn mb-3" />
                </div>
                <div>
                    <a asp-action="Index">Back to List</a>
                </div>
            </form>
        </div>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}