MoviePointProject/Models/Actor.cs
namespace MoviePoint.Models
{
    public class Actor
    {
        public int ID { get; set; }

        public string FullName { get; set; }

        public string ProfilePicUrl { get; set; }

        public string Bio { get; set;}

        public virtual List<Actor_Movie>? Actor_Movies { get; set; }
    }
}

MoviePointProject/Controllers/ActorsController.cs
using Microsoft.AspNetCore.Mvc;
using MoviePoint.Models;
using MoviePoint.Repository;

namespace MoviePoint.Controllers
{
    public class ActorsController : Controller
    {

        IActorRepository actorRepository;

        public ActorsController
            (IActorRepository _actRepo)
        {
            actorRepository = _actRepo;
        }

        public IActionResult Index()
        {
            List<Actor> actors = actorRepository.GetAll();
            return View(actors);
           
        }

        [HttpGet]
        public IActionResult Insert()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Insert(Actor Act)
        {
            if (ModelState.IsValid == true)
            {
                Actor NewActor = new Actor();
                NewActor.FullName = Act.FullName;
                NewActor.ProfilePicUrl = Act.ProfilePicUrl;
                NewActor.Bio = Act.Bio;
                actorRepository.Insert(NewActor);
                return RedirectToAction("Index");
            }
           
                return View(Act);
            
           
            
        }

        [HttpGet]
        public IActionResult Update(int id)
        {
            Actor Act = actorRepository.GetById(id);
            return View(Act);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update( int id, Actor newActor)
        {
            if (ModelState.IsValid == true)
            {
                actorRepository.Update(id,newActor);
                return RedirectToAction("Index");
            }
                return View(newActor);
                
        }

        public IActionResult Delete(int id)
        {
            actorRepository.Delete(id);
            return RedirectToAction("Index");
        }
    }
}

MoviePointProject/Views/Actors/Index.cshtml
@model IEnumerable<MoviePoint.Models.Actor>

@{
    ViewData["Title"] = "Index";
    Layout = "_NavAndFooterLayout";
}

<section class="breadcrumb-area">
	<div class="container">
		<div class="row">
			<div class="col-lg-12">
				<div class="breadcrumb-area-content">
					<h1>Actors Page</h1>
				</div>
			</div>
		</div>
	</div>
</section>

<section class="portfolio-area pt-60">
	<div class="container">
		@if (User.IsInRole("Admin"))
		{
			<div class="mx-auto text-center col-md-4">
				<a class="theme-btn" style="width:100%;" asp-action="Insert" asp-controller="Actors">Add New Actor</a>
			</div>
		}
	
		<div class="row portfolio-item">
			@foreach (var item in Model)
			{
				<div class="col-lg-3 col-md-4 col-sm-12 soon released">
					<div class="single-portfolio" style="margin-bottom:20px;">
						<div class="single-portfolio-img">
							<img src="@item.ProfilePicUrl" alt="portfolio" />
						</div>
						<div class="portfolio-content">
							<h2 class="my-3">@item.FullName</h2>
							<p class="mb-3">@item.Bio</p>
						</div>
						@if (User.IsInRole("Admin"))
						{
							<div class="d-flex justify-content-around">
								<a class="theme-btn" asp-action="Update" asp-controller="Actors" asp-route-id="@item.ID">Edit</a>
								<a class="theme-btn" asp-action="Delete" asp-controller="Actors" asp-route-id="@item.ID">Delete</a>
							</div>
						}
						
					</div>					
				</div>
			}
		</div>
	</div>
</section>

@section Scripts {
	@{
		await Html.RenderPartialAsync("_ValidationScriptsPartial");
	}
}

MoviePointProject/Views/Actors/Insert.cshtml
@model MoviePoint.Models.Actor

@{
    ViewData["Title"] = "Insert";
    Layout = "_NavAndFooterLayout";
}

<section class="breadcrumb-area">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="breadcrumb-area-content">
                    <h1>Add Actor Page</h1>
                </div>
            </div>
        </div>
    </div>
</section>
<div class="container">
    <div class="row" style="position:relative">
        <div class="col-md-5 mb-2 mx-auto">
            <form asp-action="Insert" style="position: relative;top: 50px;">
                <div asp-validation-summary="All" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="FullName" class="control-label"></label>
                    <input asp-for="FullName" class="form-control" />
                    <span asp-validation-for="FullName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ProfilePicUrl" class="control-label"></label>
                    <input asp-for="ProfilePicUrl" class="form-control" />
                    <span asp-validation-for="ProfilePicUrl" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Bio" class="control-label"></label>
                    <input asp-for="Bio" class="form-control" />
                    <span asp-validation-for="Bio" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Add" class="theme-btn mb-3" />
                </div>
                <div>
                    <a asp-action="Index">Back to List</a>
                </div>
            </form>
        </div>
    </div>
</div>




@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

MoviePointProject/Views/Actors/Update.cshtml
@model MoviePoint.Models.Actor

@{
    ViewData["Title"] = "Update";
    Layout = "_NavAndFooterLayout";
}

<section class="breadcrumb-area">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="breadcrumb-area-content">
                    <h1>Edit Actor Page</h1>
                </div>
            </div>
        </div>
    </div>
</section>

<div class="row" style="position:relative">
    <div class="col-md-5 mb-2 mx-auto">
        <form asp-action="Update" style="position: relative;top: 50px;">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FullName" class="control-label"></label>
                <input asp-for="FullName" class="form-control" />
                <span asp-validation-for="FullName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProfilePicUrl" class="control-label"></label>
                <input asp-for="ProfilePicUrl" class="form-control" />
                <span asp-validation-for="ProfilePicUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Bio" class="control-label"></label>
                <input asp-for="Bio" class="form-control" />
                <span asp-validation-for="Bio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="theme-btn mb-3" />
            </div>
            <div>
                <a asp-action="Index">Back to List</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}